### ISSUE TITLE
昨天还正常运行，挂了几晚上就开始报错了

### ISSUE THREAD

**Issue by jinxx52** [kexue-z/nonebot-plugin-setu-now#17]
`04-10 14:55:04 [SUCCESS] nonebot | ONEBOT V11 1115706211 | [message.group.normal]: Message -1337602815 from 1115706226@[群:543943710] "色图"
04-10 14:55:04 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_setu_now, type=message, priority=1, temp=False>
04-10 14:55:04 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_setu_now, type=message, priority=1, temp=False> running complete
04-10 14:55:04 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_setu_now, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "/home/nonebot/abot/bot.py", line 22, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/usr/local/python3/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/python3/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/python3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/python3/lib/python3.9/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot_plugin_setu_now/__init__.py", line 69, in _
    pic = await get_setu(key, r18)
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot_plugin_setu_now/get_data.py", line 60, in get_setu
    logger.debug(res.json())
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_models.py", line 1517, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/python3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

能解答一下吗，是我服务器自己的问题吗，昨天正常使用，然后挂了一晚上第二天开始报错，期间没有任何改动

**Comment by kexue-z** [comment]
lolicon api炸了

**Comment by jinxx52** [comment]
> lolicon api炸了

行 我觉得也是
