### ISSUE TITLE
图片保存到本地，如果图片名字中带 / 就会报错找不到目录

### ISSUE THREAD

**Issue by Zzzzzzouhang** [kexue-z/nonebot-plugin-setu-now#25]
06-07 21:43:53 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_setu_now, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/miniconda3/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/miniconda3/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/miniconda3/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/root/miniconda3/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/root/miniconda3/lib/python3.9/site-packages/nonebot_plugin_setu_now/__init__.py", line 94, in _
    await save_img(setu)
  File "/root/miniconda3/lib/python3.9/site-packages/nonebot_plugin_setu_now/save_to_local.py", line 29, in save_img
    async with await open_file(str(path), "wb+") as f:
  File "/root/miniconda3/lib/python3.9/site-packages/anyio/_core/_fileio.py", line 197, in open_file
    fp = await to_thread.run_sync(
  File "/root/miniconda3/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [Errno 2] No such file or directory: '/bot_linux/OneBot/data/setu/87293151_0_Skadi     25/1/2021_INNIYIK.jpg'

**Comment by kexue-z** [comment]
看看 `.env` 配置

**Comment by Zzzzzzouhang** [comment]
![image](https://user-images.githubusercontent.com/61148270/172399256-dc00a9af-4292-49b6-9906-059a04f24154.png)
没单独配置位置
