### ISSUE TITLE
突然报错，api检查过没有问题，默认的也不行

### ISSUE THREAD

**Issue by ability66** [kexue-z/nonebot-plugin-setu-now#49]
03-15 14:31:25 [SUCCESS] nonebot | OneBot V11 844562441 | [message.group.normal]: Message -915451022 from 2510513455@[群:512859152] '涩涩'
03-15 14:31:25 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_setu_now)
03-15 14:31:33 [WARNING] nonebot_plugin_petpet | Error downloading https://ghproxy.com/https://raw.githubusercontent.com/noneplugin/nonebot-plugin-petpet/v0.3.x/resources/resource_list.json, retry 0/3:
03-15 14:31:34 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_setu_now) running complete
03-15 14:31:34 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_setu_now) failed.
Traceback (most recent call last):
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\anyio\_core\_sockets.py", line 186, in connect_tcp
    addr_obj = ip_address(remote_host)
  File "D:\Anaconda\envs\py3-11-0\Lib\ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'image.anosu.top' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpcore\backends\asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\anyio\_core\_sockets.py", line 189, in connect_tcp
    gai_res = await getaddrinfo(
  File "D:\Anaconda\envs\py3-11-0\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Anaconda\envs\py3-11-0\Lib\socket.py", line 961, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpcore\_async\connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpcore\backends\auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpcore\backends\asyncio.py", line 109, in connect_tcp
    with map_exceptions(exc_map):
  File "D:\Anaconda\envs\py3-11-0\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Anaconda\envs\py3-11-0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "D:\Anaconda\envs\py3-11-0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "D:\Anaconda\envs\py3-11-0\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "D:\Anaconda\envs\py3-11-0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Anaconda\envs\py3-11-0\Lib\asyncio\base_events.py", line 604, in run_forever
    self._run_once()
  File "D:\Anaconda\envs\py3-11-0\Lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Anaconda\envs\py3-11-0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\nonebot_plugin_setu_now\__init__.py", line 79, in _
    data = await setu_obj.get_setu(key, tags, r18, num)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\nonebot_plugin_setu_now\data_source.py", line 67, in get_setu
    api_data = await self._get_info_from_setu_api(keyword, tags, r18, num)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\nonebot_plugin_setu_now\data_source.py", line 108, in _get_info_from_setu_api
    res = await client.post(
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpx\_client.py", line 1848, in post
    return await self.request(
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "D:\Anaconda\envs\py3-11-0\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Anaconda\envs\py3-11-0\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11002] getaddrinfo failed

**Comment by kexue-z** [comment]
httpx 的问题。具体未知。建议看看httpx的issue
