### ISSUE TITLE
正常使用一周后弹出的，之前没有任何征兆，按默认配置使用、重装插件均无法恢复,会报相同的错

### ISSUE THREAD

**Issue by 3BM59** [kexue-z/nonebot-plugin-setu-now#53]
03-29 19:03:49 [INFO] nonebot_plugin_gocqhttp | [2086429822] 收到群 群聊测试(321937753) 内 Starlight(1437153596) 的消息: 色图 (-481947562)
03-29 19:03:49 [SUCCESS] nonebot | OneBot V11 2086429822 | [message.group.normal]: Message -481947562 from 1437153596@[ 群:321937753] '色图'
03-29 19:03:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_setu_now)
03-29 19:03:50 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_setu_now) running complete
03-29 19:03:50 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_setu_now) failed.
Traceback (most recent call last):
  File "", line 17, in 
  File "D:\bot\Yohane_Bot\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\bot\Yohane_Bot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "D:\bot\Yohane_Bot\.venv\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "D:\bot\Yohane_Bot\.venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\gxgy\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\gxgy\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\gxgy\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\gxgy\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\gxgy\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\gxgy\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bot\Yohane_Bot\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\bot\Yohane_Bot\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\bot\Yohane_Bot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\bot\Yohane_Bot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "D:\bot\Yohane_Bot\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\Yohane_Bot\.venv\lib\site-packages\nonebot_plugin_setu_now\__init__.py", line 78, in _
    data = await setu_obj.get_setu(key, tags, r18, num)
  File "D:\bot\Yohane_Bot\.venv\lib\site-packages\nonebot_plugin_setu_now\data_source.py", line 67, in get_setu
    api_data = await self._get_info_from_setu_api(keyword, tags, r18, num)
  File "D:\bot\Yohane_Bot\.venv\lib\site-packages\nonebot_plugin_setu_now\data_source.py", line 111, in _get_info_from_setu_api
    data = res.json()
  File "D:\bot\Yohane_Bot\.venv\lib\site-packages\httpx\_models.py", line 755, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "C:\Users\gxgy\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\gxgy\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\gxgy\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

感谢大佬查看，这个问题超出了小白的处理范围，实在是不好意思：（

**Comment by Lover-v** [comment]
哥，你怎么解决的
