### ISSUE TITLE
ImportError: cannot import name 'ThreadLocalMetaData' from 'sqlalchemy.schema'

### ISSUE THREAD

**Issue by Kiana1314** [kexue-z/nonebot-plugin-setu-now#54]
![62N 8C9}KEP%D6`CVUL$Q@T](https://user-images.githubusercontent.com/107671434/229410942-3533ba6b-7fca-4116-97ac-1152b0d67b9f.png)

SQLAlchemy                 2.0.7
sqlalchemy2-stubs          0.0.2a32
sqlmodel                   0.0.8

**Comment by kexue-z** [comment]
@OREOCODEDEV  出来背锅

**Comment by OREOCODEDEV** [comment]
setu-now的版本号是多少？Bot目录下使用命令`nb plugin install nonebot-plugin-setu-now --upgrade --pre -i https://pypi.org/simple`看看

**Comment by Kiana1314** [comment]
仓库直接git的

> setu-now的版本号是多少？Bot目录下载使用命令`nb plugin install nonebot-plugin-setu-now --upgrade --pre -i https://pypi.org/simple`看

**Comment by Kiana1314** [comment]
git pull后启动无报错，但是使用涩图指令报错了：

04-03 15:52:54 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-setu-now.nonebot_plugin_setu_now) failed.
Traceback (most recent call last):
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\engine\default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 254, in _handle_exception
    raise error
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "D:\bot\NB2\venv\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "D:\bot\NB2\venv\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "D:\bot\NB2\venv\lib\site-packages\aiosqlite\core.py", line 137, in _execute
    return await future
  File "D:\bot\NB2\venv\lib\site-packages\aiosqlite\core.py", line 110, in run
    result = function()
sqlite3.OperationalError: no such table: white_list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\bot\NB2\yule\bot.py", line 70, in <module>
    nonebot.run(app="__mp_main__:app")
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "D:\bot\NB2\venv\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\bot\NB2\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\clb\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\clb\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\clb\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\clb\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\clb\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\clb\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\bot\NB2\venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 104, in __call__
    values = await self.solve(**kwargs)
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 219, in solve
    values = await asyncio.gather(
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 208, in _solve_field
    value = await cast(Param, field.field_info)._solve(**params)
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\internal\params.py", line 144, in _solve
    return await task
  File "D:\bot\NB2\yule\nonebot-plugin-setu-now\nonebot_plugin_setu_now\r18_whitelist.py", line 21, in get_group_white_list_record
    result = (await db_session.scalars(statement)).first()  # type: ignore
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 431, in scalars
    result = await self.execute(
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 313, in execute
    result = await greenlet_spawn(
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 165, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2229, in execute
    return self._execute_internal(
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\orm\context.py", line 253, in orm_execute_statement
    result = conn.execute(
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute
    return meth(
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\engine\default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 254, in _handle_exception
    raise error
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "D:\bot\NB2\venv\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "D:\bot\NB2\venv\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "D:\bot\NB2\venv\lib\site-packages\aiosqlite\core.py", line 137, in _execute
    return await future
  File "D:\bot\NB2\venv\lib\site-packages\aiosqlite\core.py", line 110, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: white_list
[SQL: SELECT white_list.group_id, white_list.operator_user_id
FROM white_list
WHERE white_list.group_id = ?]
[parameters: (950180960,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by Kiana1314** [comment]
通过nb plugin install nonebot-plugin-setu-now安装已能出图

**Comment by kexue-z** [comment]
> 通过nb plugin install nonebot-plugin-setu-now安装已能出图

pypi上是旧版（ 0.4.4

新的还在测试版 0.5.0.a2

**Comment by wling-art** [comment]
我在0.6.4又遇到了这个问题，他貌似又随机性的链接，或者会跟[nonebot-plugin-learning-chat](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat)冲突
```
08-21 07:40:41 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_setu_now) failed.
Traceback (most recent call last):
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/tortoise/backends/sqlite/client.py", line 34, in translate_exceptions_
    return await func(self, query, *args)
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/tortoise/backends/sqlite/client.py", line 141, in execute_query
    rows = await connection.execute_fetchall(query, values)
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/aiosqlite/core.py", line 203, in execute_fetchall
    return await self._execute(self._execute_fetchall, sql, parameters)
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/aiosqlite/core.py", line 81, in _execute_fetchall
    cursor = self._conn.execute(sql, parameters)
sqlite3.OperationalError: no such table: white_list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/bot.py", line 16, in <module>
    nonebot.run()
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/python3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/nonebot/message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/nonebot/message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 104, in __call__
    values = await self.solve(**kwargs)
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 219, in solve
    values = await asyncio.gather(
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 208, in _solve_field
    value = await cast(Param, field.field_info)._solve(**params)
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/nonebot/internal/params.py", line 163, in _solve
    return await task
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/nonebot_plugin_setu_now/r18_whitelist.py", line 15, in get_group_white_list_record
    res = await GroupWhiteListRecord.get_or_none(group_id=event.group_id)
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/tortoise/queryset.py", line 1008, in _execute
    instance_list = await self._db.executor_class(
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/tortoise/backends/base/executor.py", line 131, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "/opt/mcsmanager/daemon/data/InstanceData/40b38bc1982f4f11bf8699aa8e402347/.venv/lib/python3.10/site-packages/tortoise/backends/sqlite/client.py", line 36, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: no such table: white_list
```
