### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by a1232580** [kexue-z/nonebot-plugin-setu-now#56]
06-13 23:39:13 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_setu_now) failed.                          Traceback (most recent call last):                                 File "<string>", line 15, in <module>                            File "/root/df/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run                                            get_driver().run(*args, **kwargs)                              File "/root/df/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run                                     uvicorn.run(                                                   File "/root/df/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run                                                server.run()                                                   File "/root/df/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run                                               return asyncio.run(self.serve(sockets=sockets))                File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run     return loop.run_until_complete(main)                           File "/root/df/.venv/lib/python3.10/site-packages/nonebot/message.py", line 467, in check_and_run_matcher                           await _run_matcher(                                          > File "/root/df/.venv/lib/python3.10/site-packages/nonebot/message.py", line 419, in _run_matcher                                    await matcher.run(bot, event, state, stack, dependency_cache)  File "/root/df/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run                            await self.simple_run(bot, event, state, stack, dependency_cache)                                                               File "/root/df/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run                     await handler(                                                 File "/root/df/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__                          return await cast(Callable[..., Awaitable[R]], self.call)(**values)                                                             File "/root/df/.venv/lib/python3.10/site-packages/nonebot_plugin_setu_now/__init__.py", line 51, in _                               args = list(state["_matched_groups"])                        KeyError: '_matched_groups'

**Comment by Agnes4m** [comment]
同报错，版本0.4.4
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot_plugin_reboot/reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot_plugin_setu_now/__init__.py", line 51, in _
    args = list(state["_matched_groups"])
KeyError: '_matched_groups'
```

**Comment by kexue-z** [comment]
摆了，更新一下 0.5.0-alpha.2 吧

**Comment by a1232580** [comment]
> 

为啥现在只返回图片？
而且多张的话不是转发的了
是一张一张图发

**Comment by kexue-z** [comment]
因为考虑到合并转发可能会增大风控几率，并且已经添加了新的图片处理方法防止发不出。所以合并转发取消了

另外，要获取图片信息的话，直接回复该图片并指令 信息 即可
