### ISSUE TITLE
安装后报错

### ISSUE THREAD

**Issue by EXarchive** [kexue-z/nonebot-plugin-setu-now#62]
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    yunzai_nonebot.load_plugin(plugin.replace("-", "_"))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-p8kRwHxt-py3.8\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\Administrator\Miao-Yunzai\plugins\py-plugin\yunzai_nonebot\hijack\plugin.py", line 16, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-p8kRwHxt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-p8kRwHxt-py3.8\lib\site-packages\nonebot_plugin_setu_now\__init__.py", line 8, in <module>
    from typing import Any, Union, Annotated
ImportError: cannot import name 'Annotated' from 'typing' (C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\typing.py)

**Comment by kexue-z** [comment]
更新py版本到3.10以上
要不就修改代码以兼容旧版
> From: ***@***.***>
> Date:  Sat, Sep 30, 18:18
> Subject:  [kexue-z/nonebot-plugin-setu-now] 安装后报错 (Issue #62)
> To: ***@***.***>
> Cc: ***@***.***>
> Traceback (most recent call last):
> 
File "main.py<http://main.py>", line 15, in 
> 
yunzai_nonebot.load_plugin(plugin.replace("-", "_"))
> 
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-p8kRwHxt-py3.8\lib\site-packages\nonebot\plugin\load.py<http://load.py>", line 39, in load_plugin
> 
return manager.load_plugin(module_path)
> > File "C:\Users\Administrator\Miao-Yunzai\plugins\py-plugin\yunzai_nonebot\hijack\plugin.py<http://plugin.py>", line 16, in load_plugin
> > 
module = importlib.import_module(name)
> > 
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib_init_.py<http://_.py>", line 127, in import_module
> > 
return _bootstrap._gcd_import(name[level:], package, level)
> > 
File "", line 1014, in _gcd_import
> > 
File "", line 991, in _find_and_load
> > 
File "", line 975, in _find_and_load_unlocked
> > 
File "", line 671, in _load_unlocked
> > 
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-p8kRwHxt-py3.8\lib\site-packages\nonebot\plugin\manager.py<http://manager.py>", line 242, in exec_module
> > 
super().exec_module(module)
> > 
File "", line 848, in exec_module
> > 
File "", line 219, in call_with_frames_removed
> > 
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-p8kRwHxt-py3.8\lib\site-packages\nonebot_plugin_setu_now_init.py", line 8, in 
> > 
from typing import Any, Union, Annotated
