### ISSUE TITLE
在群里发送/开启色色时报错

### ISSUE THREAD

**Issue by Octopus058** [kexue-z/nonebot-plugin-setu-now#66]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Python310\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "D:\Python310\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python310\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\Python310\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
    await handler(
  File "D:\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Desktop\QQbot\Oct\src\plugins\nonebot_plugin_setu_now\r18_whitelist.py", line 27, in _
    if _ := await GroupWhiteListRecord.get_or_none(group_id=event.group_id):
  File "D:\Python310\lib\site-packages\tortoise\models.py", line 1348, in get_or_none
    db = using_db or cls._choose_db()
  File "D:\Python310\lib\site-packages\tortoise\models.py", line 1035, in _choose_db
    return db or cls._meta.db
  File "D:\Python310\lib\site-packages\tortoise\models.py", line 286, in db
    raise ConfigurationError(
tortoise.exceptions.ConfigurationError: default_connection for the model <class 'src.plugins.nonebot_plugin_setu_now.database.GroupWhiteListRecord'> cannot be None

**Comment by Qu1n-22** [comment]
有这个问题+1
