### ISSUE TITLE
安装过程报错

### ISSUE THREAD

**Issue by Readedd** [kexue-z/nonebot-plugin-setu-now#67]
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\qqbot\setubot\.venv\include -ID:\python\include -ID:\python\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tcasyncmy\charset.c /FoC:\Users\MiraiSaki\AppData\Local\Temp\pip-install-g5cb78t8\asyncmy_b367b10da5224abf9c5c805e9f7f89f8\build\temp.win-amd64-cpython-312\Release\asyncmy\charset.obj
      charset.c
      D:\python\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: “io.h”: No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      Traceback (most recent call last):
        File "D:\qqbot\setubot\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\qqbot\setubot\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\qqbot\setubot\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MiraiSaki\AppData\Local\Temp\pip-build-env-grhc3c3u\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 58, in build_wheel
          return WheelBuilder.make_in(
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MiraiSaki\AppData\Local\Temp\pip-build-env-grhc3c3u\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "C:\Users\MiraiSaki\AppData\Local\Temp\pip-build-env-grhc3c3u\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 121, in build
          self._build(zip_file)
        File "C:\Users\MiraiSaki\AppData\Local\Temp\pip-build-env-grhc3c3u\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 182, in _build
          self._run_build_command(setup)
        File "C:\Users\MiraiSaki\AppData\Local\Temp\pip-build-env-grhc3c3u\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 248, in _run_build_command
          subprocess.check_call([
        File "D:\python\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['D:/qqbot/setubot/.venv/Scripts/python.exe', 'C:\\Users\\MiraiSaki\\AppData\\Local\\Temp\\pip-install-g5cb78t8\\asyncmy_b367b10da5224abf9c5c805e9f7f89f8\\setup.py', 'build', '-b', 'C:\\Users\\MiraiSaki\\AppData\\Local\\Temp\\pip-install-g5cb78t8\\asyncmy_b367b10da5224abf9c5c805e9f7f89f8\\build', '--build-purelib', 'C:\\Users\\MiraiSaki\\AppData\\Local\\Temp\\pip-install-g5cb78t8\\asyncmy_b367b10da5224abf9c5c805e9f7f89f8\\build\\lib', '--build-platlib', 'C:\\Users\\MiraiSaki\\AppData\\Local\\Temp\\pip-install-g5cb78t8\\asyncmy_b367b10da5224abf9c5c805e9f7f89f8\\build\\lib.win-amd64-cpython-312']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for asyncmy
Failed to build asyncmy
ERROR: Could not build wheels for asyncmy, which is required to install pyproject.toml-based projects

py版本3.12.2

**Comment by kexue-z** [comment]
msvc环境问题吧，建议重装
